name: stocks
description: Flutter stocks app.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^5.0.1
  autoequal: ^0.4.0
  bloc_event_transformers: ^1.0.1
  collection: ^1.16.0
  copy_with_extension: ^4.0.0
  d_chart: ^0.1.0
  dio: ^5.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  json_annotation: ^4.7.0

dev_dependencies:
  auto_route_generator: ^5.0.2
  autoequal_gen: ^0.4.0
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  copy_with_extension_gen: ^4.0.1
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.0.5
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.5.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
